
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tilt.op.tilt.dev
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tilt.op.tilt.dev
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tilt.op.tilt.dev
  resources:
  - webs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tilt.op.tilt.dev
  resources:
  - webs/status
  verbs:
  - get
  - patch
  - update
